# ----------- CONFIGURABLE START -----------
title:            "Scribble"
title:            "A DASH OF INDHY"
description:      "Such theme, very cool."
url:              http://scribble.muan.co # Site url, without a slash at the end.
signoff:          "muan" # Your name
@@ -19,4 +19,4 @@ links:
permalink:        /posts/:title
defaults:
  - values:
      layout: "default" 
      layout: "default"
