# Permalinks
permalink:           pretty

# Setup
title:               Indhira Holmes
tagline:             UX Designer
url:               IndhiraHolmes.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Indhira Holmes
  url:               https://twitter.com/
  email:             iindhira@gmail.com
  place:             the DMV
  more_info:         User experience is about being diligent, practical and exploratory. Figuring out the user’s needs is key in the process of creating a frictionless experience with a product. Let’s work together to unite users and products, design and experience.

# Custom vars
version:             2.0.1
# github:
#   repo:              https://github.com/iindhira/portfolio
google_analytics:    FAKE_GOOGLE_ANALYTICS
twitter:             
github:              iindhira
dribbble:            iindhira

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
